server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/csa-web?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ctsi2019
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.example.demo.entity